apiVersion: v1
kind: Service
metadata:
  name: {{ include "zulip.componentName" (dict "root" . "component" "memcached") }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: ClusterIP
  selector:
    {{- include "zulip.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
  ports:
    - name: memcached
      port: 11211
      targetPort: memcached
      protocol: TCP
