apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zulip.componentName" (dict "root" . "component" "postgres") }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "zulip.componentName" (dict "root" . "component" "postgres") }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "zulip.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "zulip.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.images.postgres }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: "zulip"
            - name: POSTGRES_USER
              value: "zulip"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: postgres_password
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "zulip.labels" . | nindent 10 }}
          app.kubernetes.io/component: postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.postgres.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
