apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zulip.componentName" (dict "root" . "component" "rabbitmq") }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zulip.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "zulip.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.images.rabbitmq }}
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "zulip"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: rabbitmq_password
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.rabbitmq | nindent 12 }}
