apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zulip.componentName" (dict "root" . "component" "redis") }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zulip.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "zulip.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.images.redis }}
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -ec
            - exec redis-server --requirepass "$REDIS_PASSWORD" --protected-mode yes
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: redis_password
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.redis | nindent 12 }}
