apiVersion: v1
kind: Service
metadata:
  name: {{ include "zulip.fullname" . }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "zulip.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zulip
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
