apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zulip.componentName" (dict "root" . "component" "uploads") }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
